/**
 * ============================================================================
 * DISPATCHING EVENTS
 * ============================================================================
 *
 * We can create and dispatch events manually with JavaScript.
 *
 * ============================================================================
 * EVENT
 * ============================================================================
 *
 * Create a basic event:
 *
 *   const event = new Event("hello");
 *
 * Dispatch it:
 *
 *   element.dispatchEvent(event);
 *
 * This triggers the handlers registered for "hello".
 *
 * ============================================================================
 * BUBBLES
 * ============================================================================
 *
 * Custom events do NOT bubble by default.
 *
 * Enable bubbling:
 *
 *   const event = new Event("hello", {
 *       bubbles: true
 *   });
 *
 * Now the event can bubble from the target to its ancestors.
 *
 * ============================================================================
 * CANCELABLE
 * ============================================================================
 *
 *   const event = new Event("hello", {
 *       cancelable: true
 *   });
 *
 * This allows handlers to call:
 *
 *   event.preventDefault();
 *
 * ============================================================================
 * CUSTOM EVENT
 * ============================================================================
 *
 * CustomEvent is useful when we want to create
 * our own application-specific events.
 *
 *   const event = new CustomEvent("hello");
 *
 * ============================================================================
 * DETAIL
 * ============================================================================
 *
 * CustomEvent can carry custom data through "detail".
 *
 *   const event = new CustomEvent("hello", {
 *       detail: {
 *           name: "Misaq"
 *       }
 *   });
 *
 * Read the data:
 *
 *   element.addEventListener("hello", (event) => {
 *       console.log(event.detail.name);
 *   });
 *
 * ============================================================================
 * SPECIALIZED EVENTS
 * ============================================================================
 *
 * Different event types have specialized constructors.
 *
 *   new MouseEvent("click", options);
 *   new KeyboardEvent("keydown", options);
 *
 * They provide properties specific to those event types.
 *
 * ============================================================================
 * IS TRUSTED
 * ============================================================================
 *
 * event.isTrusted
 *
 *   true  → event came from a real user action.
 *   false → event was generated by JavaScript.
 *
 * ============================================================================
 * DISPATCHEVENT RETURN VALUE
 * ============================================================================
 *
 * dispatchEvent() returns:
 *
 *   true
 *   → event was not prevented.
 *
 *   false
 *   → event was prevented with preventDefault().
 *
 * This works when the event is cancelable.
 *
 * ============================================================================
 * NESTED EVENTS
 * ============================================================================
 *
 * dispatchEvent() is synchronous.
 *
 * If an event dispatches another event:
 *
 *   console.log("1");
 *   element.dispatchEvent(event);
 *   console.log("2");
 *
 * The handlers of the dispatched event run immediately.
 *
 * ============================================================================
 * MAIN MENTAL MODEL
 * ============================================================================
 *
 * new Event()
 * → Create an event.
 *
 * new CustomEvent()
 * → Create a custom event with optional detail data.
 *
 * dispatchEvent()
 * → Dispatch the event on an element.
 *
 * bubbles: true
 * → Allow the event to bubble.
 *
 * cancelable: true
 * → Allow preventDefault().
 *
 * event.detail
 * → Custom data carried by CustomEvent.
 *
 * event.isTrusted
 * → Check whether the event came from a real user action.
 *
 * ============================================================================
 */

